<a href="https://colab.research.google.com/github/kimvongola/Self-Study-ML/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocessing Code Example

### Part I: Set ups
This part includes the imported libraries and dataset. Feel free to change the path of the dataset accordingly.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/FRA 503  Machine Learning /Coding/Raw dataset/adult.data', header = None)

In [ ]:
df.columns = ['age', 'workclass', 'fnlwgt', 'edu', 'edu-num', 'marital', 'occupation', 'relationship', 'race', 'sex', 'cap-gain', 'cap-loss','hpw','native country','income']

In [ ]:
df.head()

age          workclass  fnlwgt         edu  edu-num              marital  \
0   39          State-gov   77516   Bachelors       13        Never-married   
1   50   Self-emp-not-inc   83311   Bachelors       13   Married-civ-spouse   
2   38            Private  215646     HS-grad        9             Divorced   
3   53            Private  234721        11th        7   Married-civ-spouse   
4   28            Private  338409   Bachelors       13   Married-civ-spouse   

           occupation    relationship    race      sex  cap-gain  cap-loss  \
0        Adm-clerical   Not-in-family   White     Male      2174         0   
1     Exec-managerial         Husband   White     Male         0         0   
2   Handlers-cleaners   Not-in-family   White     Male         0         0   
3   Handlers-cleaners         Husband   Black     Male         0         0   
4      Prof-specialty            Wife   Black   Female         0         0   

   hpw  native country  income  
0   40   United-States   <=50K  
1   13   United-States   <=50K  
2   40   United-States   <=50K  
3   40   United-States   <=50K  
4   40            Cuba   <=50K

### Part II: Basic Data Understanding

We can look at all values and their counts by using the following code. It is useful to understand all aspect of the dataset.

In [ ]:
# df['workclass'].value_counts()
df['edu'].value_counts()

edu
 HS-grad         10501
 Some-college     7291
 Bachelors        5355
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: count, dtype: int64

### Part III: Preprocessing

The following lines of code show how you can normalize the data. Noted that if you want to normalize only one feature, you need to change the datatype accordingly.

You can create a new dataframe with one feature by using old_df[['feature_name']]

More info at https://scikit-learn.org/stable/modules/preprocessing.html

In [ ]:
df2 = df[['age']]
print(df2)
from sklearn import preprocessing
import numpy as np

min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler.fit_transform(df2)

       age
0       39
1       50
2       38
3       53
4       28
...    ...
32556   27
32557   40
32558   58
32559   22
32560   52

[32561 rows x 1 columns]


array([[0.30136986],
       [0.45205479],
       [0.28767123],
       ...,
       [0.56164384],
       [0.06849315],
       [0.47945205]])

Or you can change from array (df['feature_name']) to numpy array by using np.array()

In [ ]:
x_scaled2=min_max_scaler.fit_transform(np.array(df['age']).reshape(-1, 1))

In [ ]:
x_scaled2

array([[0.30136986],
       [0.45205479],
       [0.28767123],
       ...,
       [0.56164384],
       [0.06849315],
       [0.47945205]])

To preform one-hot encoding for categorical feature, you can use the following lines of code.

More info at https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

In [ ]:
df3 = df[['edu']]
df4 = pd.get_dummies(df3)

In [ ]:
df4.head()

edu_ 10th  edu_ 11th  edu_ 12th  edu_ 1st-4th  edu_ 5th-6th  edu_ 7th-8th  \
0      False      False      False         False         False         False   
1      False      False      False         False         False         False   
2      False      False      False         False         False         False   
3      False       True      False         False         False         False   
4      False      False      False         False         False         False   

   edu_ 9th  edu_ Assoc-acdm  edu_ Assoc-voc  edu_ Bachelors  edu_ Doctorate  \
0     False            False           False            True           False   
1     False            False           False            True           False   
2     False            False           False           False           False   
3     False            False           False           False           False   
4     False            False           False            True           False   

   edu_ HS-grad  edu_ Masters  edu_ Preschool  edu_ Prof-school  \
0         False         False           False             False   
1         False         False           False             False   
2          True         False           False             False   
3         False         False           False             False   
4         False         False           False             False   

   edu_ Some-college  
0              False  
1              False  
2              False  
3              False  
4              False

You can also perform feature selection on the whole dataframe.

More info at https://scikit-learn.org/stable/modules/feature_selection.html

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

x = df.iloc[:,:-1]    #Split only data
y = df.iloc[:,-1] #df[['income']]     #Split the target out

In [ ]:
df[['income']]

income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 1 columns]

In [ ]:
print(x)

       age  fnlwgt  edu-num  cap-gain  cap-loss  hpw  workclass_ ?  \
0       39   77516       13      2174         0   40         False   
1       50   83311       13         0         0   13         False   
2       38  215646        9         0         0   40         False   
3       53  234721        7         0         0   40         False   
4       28  338409       13         0         0   40         False   
...    ...     ...      ...       ...       ...  ...           ...   
32556   27  257302       12         0         0   38         False   
32557   40  154374        9         0         0   40         False   
32558   58  151910        9         0         0   40         False   
32559   22  201490        9         0         0   20         False   
32560   52  287927        9     15024         0   40         False   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                       False                 False                    False   

In [ ]:
print(y)

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
32556     <=50K
32557      >50K
32558     <=50K
32559     <=50K
32560      >50K
Name: income, Length: 32561, dtype: object


In [ ]:
# We can one-hot encode the dataframe. This line of code will encode only categorical features automatically.
x = pd.get_dummies(x)

# We then create the feature selector. In this case, we use chi-2 algorithm and we want to choose 4 features (k=4).
selector = SelectKBest(chi2, k=4)     #This line creates the selector
x_new = selector.fit(x,y)             #This line fits the selector to the dataset, and select the features.

# Once we fit the selector, all features are selected and its indices are saved. We can create a new dataframe with those indices.
col = selector.get_support(indices=True)   #all indices are saved in col.
x_new = x.iloc[:,col]

In [ ]:
x_new.head()

age  fnlwgt  cap-gain  cap-loss
0   39   77516      2174         0
1   50   83311         0         0
2   38  215646         0         0
3   53  234721         0         0
4   28  338409         0         0

You can also perform feature extraction.

More info at https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 4)           # Create PCA transformer
x_pca = pca.fit_transform(x)          # Fit and transform PCA transformer to the dataset

print(pca.explained_variance_ratio_)  # This show the variance of each component.

[9.95113642e-01 4.87183949e-03 1.44878114e-05 1.66233329e-08]


The array above shows the explained variance of each component. The first element is 0.99511. It means that the first component can explain 99.51% of the dataset already. Thus, it means that we can reduce the dimension of the original dataset to only 1 feature that basically covers 99.51% of the data.

In [ ]:
pd.DataFrame(x_pca).head()

0            1          2          3
0 -112262.329664  1099.917213 -89.796475  -0.815179
1 -106467.395741 -1074.257792 -93.353761   2.959664
2   25867.604154 -1078.283626 -88.157906  -0.024219
3   44942.603983 -1078.862069 -87.382449  14.597705
4  148630.604092 -1082.021023 -83.374483  -8.370771